sudo: required

services:
  - docker

script:
  - docker build -t ci_builder tools/ci-docker/
  - docker run -it -v $(pwd):/catkin_ws/src/robosub ci_builder catkin_make
  - docker run -it -v $(pwd):/catkin_ws/src/robosub ci_builder catkin_make run_tests
